### ISSUE TITLE
Asset-reference bare-specifier resolver fails on Windows (regression in 0.1.36)

### ISSUE THREAD

**Issue by jdutton** [jdutton/vibe-agent-toolkit#102]
## Summary

`vat resources validate` link-integrity step fails on Windows when a markdown file references an asset by Node bare specifier (e.g. `@scope/pkg/path/to/file.json`). The same configuration and content pass on macOS and Ubuntu.

This is a regression in the asset-reference resolver introduced alongside the new bare-specifier support in `0.1.36` — `frontmatterSchema` resolution itself works on Windows in `0.1.36`, but the link-integrity codepath that resolves bare-specifier asset references inside markdown content does not.

## Versions

- `@vibe-agent-toolkit/cli`: 0.1.36
- `@vibe-agent-toolkit/resources`: 0.1.36
- Node: 22.x
- pnpm: 10.x
- OS where it fails: `windows-latest` (GitHub Actions, Windows Server 2022)
- OS where it passes: `ubuntu-latest`, `macos-latest`

## Symptom

CI step output on Windows:

```
- name: Link integrity
  command: pnpm exec vat resources validate
  passed: false
  durationSecs: 13.4
  exitCode: 2
  errorSummary: >-
    status: error
    error: >-
      Failed to resolve asset reference '@scope/example-package/schemas/foo.schema.json':
      Cannot find module
```

Same command on macOS and Ubuntu returns `status: success`.

## Reproduction

1. In a workspace repo with package `@scope/example-package` published as a workspace dep at the root (so `node_modules/@scope/example-package` is symlinked at the consumer root) and an `exports` map of the form:

   ```json
   {
     "name": "@scope/example-package",
     "exports": {
       "./schemas/*.json": "./dist/schemas/*.json"
     }
   }
   ```

2. Author any markdown file at the root that references the asset by bare specifier:

   ```markdown
   | Schema | `@scope/example-package/schemas/foo.schema.json` |
   ```

3. Configure `vibe-agent-toolkit.config.yaml`:

   ```yaml
   version: 1
   resources:
     include: ["**/*.md"]
     validation:
       checkLinks: true
       allowExternal: true
     collections:
       things:
         include: ["docs/things/**/*.md"]
         validation:
           frontmatterSchema: \"@scope/example-package/schemas/foo.schema.json\"
           mode: permissive
   ```

4. Build the workspace so `node_modules/@scope/example-package/dist/schemas/foo.schema.json` is present and the exports subpath resolves.

5. Run `pnpm exec vat resources validate` on each platform.

**Expected:** `status: success` on all platforms (since the same bare specifier resolves cleanly via the package's `exports` subpath pattern on all platforms when used with `require.resolve` / `import.meta.resolve` from the workspace root).

**Actual:** Passes on Linux + macOS; fails on Windows with `Failed to resolve asset reference '@scope/example-package/schemas/foo.schema.json': Cannot find module`.

## Suspected cause

The asset-reference resolver in `@vibe-agent-toolkit/resources` (the codepath that validates inline asset citations in markdown content for link integrity, as distinct from the `frontmatterSchema` resolver added in `0.1.36`) likely assembles the lookup path using POSIX-style joins or `path.join` without converting Windows drive-letter paths to `file://` URLs before calling the underlying Node resolver.

On Windows, `createRequire(pathToFileURL(path.join(baseDir, 'package.json')).href).resolve(specifier)` works when:
- `baseDir` is converted via `pathToFileURL` (handles `D:\\…` correctly)
- The resolver is given the bare specifier unchanged (Node honors the package's `exports` map)

It does NOT work when:
- The lookup path is built by string-concatenating `baseDir` (a Windows path with `\\`) with the bare specifier — yielding an invalid path that's neither a Windows path nor a Node module specifier
- `pathToFileURL` is applied to the joined string rather than to `baseDir` alone

The fact that `frontmatterSchema` works on Windows in `0.1.36` but link-integrity asset references do not suggests the two resolvers share concept but not implementation — only the `frontmatterSchema` path was updated to use the new bare-specifier resolver.

## Suggested fix

Unify on a single helper (e.g. `resolveSchemaPath(specifier, baseDir)` exported from `@vibe-agent-toolkit/utils`) used by both `frontmatterSchema` and the link-integrity asset-reference resolver. Implementation reference:

\`\`\`ts
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
import path from 'node:path';

const BARE_SPECIFIER_RE = /^(?:@[^/]+\\/[^/]+|[^./@][^/]*)\\/.+/;

export function resolveAsset(specifier: string, baseDir: string): string {
  if (BARE_SPECIFIER_RE.test(specifier)) {
    const require = createRequire(pathToFileURL(path.join(baseDir, 'package.json')).href);
    return require.resolve(specifier);
  }
  return path.resolve(baseDir, specifier);
}
\`\`\`

The key cross-platform invariant is: pass `baseDir` through `pathToFileURL` *before* `createRequire`, and let Node's resolver consume the bare specifier directly — never join the bare specifier into a filesystem path manually.

## Impact

Any workspace consuming \`@vibe-agent-toolkit/resources\` 0.1.36 on a Windows CI matrix entry will fail link-integrity validation when markdown content cites assets via Node bare specifiers — even though the same content passes on POSIX runners.

Workarounds in user repos:
- Revert markdown content to filesystem-relative paths (defeats the migration to bare specifiers)
- Skip the Windows matrix entry (loses Windows coverage)
- Pin to \`@vibe-agent-toolkit/*\` 0.1.35 (loses the new bare-specifier feature entirely)

Fixing the asset-reference resolver in \`0.1.37\` would let consumers complete the package-subpath migration uniformly across platforms.

**Comment by jdutton** [comment]
Fixed in #103 (merged 2026-05-16, commit 4b6d66e3). The PR title referenced this issue but didn't include a `Closes` keyword, so it was left open inadvertently.
